
name:        flatparse
version:     0.5.3.0
license:     MIT
category:    Parsing
synopsis:    High-performance parsing from strict bytestrings
author:      Andr치s Kov치cs
maintainer:  puttamalac@gmail.com
copyright:   2021 Andr치s Kov치cs
bug-reports: https://github.com/AndrasKovacs/flatparse/issues
github:      AndrasKovacs/flatparse

description: |
  @Flatparse@ is a high-performance parsing library for strict bytestring input. See the README for more information:
  <https://github.com/AndrasKovacs/flatparse>.

tested-with:
  - GHC == 8.6.5
  - GHC == 8.8.4
  - GHC == 8.10.7
  - GHC == 9.0.2
  - GHC == 9.2.8
  - GHC == 9.4.8
  - GHC == 9.6.7
  - GHC == 9.8.4

flags:
  llvm:
    description: use llvm for building
    default: false
    manual : true
  dump:
    description: dump core, stg and cmm to files
    default: false
    manual: true

dependencies:
  - base >= 4.7 && < 5
  - utf8-string ^>= 1.0.2

extra-source-files:
  - README.md

default-extensions:
  - BangPatterns
  - BlockArguments
  - CPP
  - ExplicitNamespaces
  - LambdaCase
  - MagicHash
  - OverloadedStrings
  - PatternSynonyms
  - TemplateHaskell
  - TupleSections

ghc-options:
  - -Wall
  - -Wno-missing-signatures
  - -Wno-name-shadowing
  - -Wno-unused-binds
  - -Wno-unused-matches

when:
  - condition: flag(dump)
    ghc-options:
      - -ddump-simpl
      - -ddump-stg-final
      - -ddump-cmm
      - -dsuppress-all
      - -dno-suppress-type-signatures
      - -ddump-to-file

  - condition: flag(llvm)
    ghc-options:
      - -fllvm

library:
  source-dirs:
    - src
  dependencies:
    - bytestring
    - containers
    - integer-gmp
    - template-haskell
  ghc-options:
    - -O2

tests:
  spec:
    main: Test.hs
    source-dirs:
      - test
    dependencies:
      - HUnit
      - bytestring
      - flatparse
      - hspec
      - QuickCheck
      - quickcheck-instances
    default-extensions:
      - ExtendedDefaultRules
    ghc-options:
      - -O2
      - -Wno-type-defaults

benchmarks:
  bench:
    source-dirs: bench
    main: Bench.hs
    dependencies:
      - attoparsec
      - bytestring
      - flatparse
      - integer-gmp
      - megaparsec
      - parsec
      - primitive
      - tasty-bench
    ghc-options:
      - -O2
